JoJo/src/java/uts/aip/CuuSonDang/Controller/JournalController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts.aip.CuuSonDang.Controller;

import java.io.Serializable;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.naming.NamingException;
import javax.servlet.http.HttpServletRequest;
import uts.aip.CuuSonDang.DAO.EntryDAO;
import uts.aip.CuuSonDang.DAO.JournalDAO;
import uts.aip.CuuSonDang.DTO.EntryDTO;
import uts.aip.CuuSonDang.DTO.JournalDTO;

/**
 * This class represents a controller that will be used to perform action related to journals as well as the entries of the journals
 * @author Cuu Son Dang
 */
@Named
@SessionScoped
public class JournalController implements Serializable {
    private JournalDTO journal = new JournalDTO();
    private List<JournalDTO> journalList = new ArrayList<>();
    private JournalDAO journalDAO = new JournalDAO();
    private boolean isModifiable = false;
    private Map<Long, Boolean> checkedJournals = new HashMap<Long, Boolean>();
    private String searchKey;
    
    private EntryDTO entry = new EntryDTO();
    private EntryDAO entryDAO = new EntryDAO();

    private static final Object syncRoot = new Object();
    
    /**
     * An entry which belong to a journal. This entry is used to load an entry for editing
     * @return an entry that can be used for editing
     */
    public EntryDTO getEntry() {
        return entry;
    }

    public void setEntry(EntryDTO entry) {
        this.entry = entry;
    }
    
    /**
     * Indicate if the current user can modify a journal as well as the entries of that journal or not
     * @return true if the user can modify the journal and its entries, false otherwise.
     */
    public boolean getIsModifiable(){
        return isModifiable;
    }
    
    /**
     * Indicate if the current user can delete a journal as well as the entries of that journal or not
     * @return true if the user can delete the journal and its entries, false otherwise.
     */
    public boolean getIsRemovable(){
        return getIsModifiable();
    }
    
    /**
     * The main journal that the user work with when edit journal, or view/add/edit entries belong to a journal
     * @return a journal with empty entry list when edit journal, or a journal with full entry list when view/add/edit entries belong to it.
     */
    public JournalDTO getJournal() {
        return journal;
    }

    public void setJournal(JournalDTO journal) {
        this.journal = journal;
    }

    /**
     * A list of journals that will be used when: user view their journals, or when they search journals using the quick search form
     * @return a list of journals that match the describe condition. Return an empty list if no journals is matched.
     */
    public List<JournalDTO> getJournalList() {
        return journalList;
    }

    public void setJournalList(List<JournalDTO> journalList) {
        this.journalList = journalList;
    }

    /**
     * A map of journal IDs and their status indicate if the user has selected the journals for delete or not
     * @return 
     */
    public Map<Long, Boolean> getCheckedJournals() {
        return checkedJournals;
    }

    public void setCheckedJournals(Map<Long, Boolean> checkedJournals) {
        this.checkedJournals = checkedJournals;
    }

    /**
     * The search key from the quick search from
     * @return 
     */
    public String getSearchKey() {
        return searchKey;
    }

    public void setSearchKey(String searchKey) {
        this.searchKey = searchKey;
    }
    
    /**
     * Create a new journal. The author of the journal is the current logged in user.
     * @return a view that display the newly created journal
     * @throws SQLException
     * @throws NamingException 
     */
    public String createNewJournal() throws SQLException, NamingException{
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest)context.getExternalContext().getRequest();
        String author = request.getRemoteUser();
        journal.setAuthor(author);
        long journalID = journalDAO.createJournal(journal);
        return viewJournal(journalID);
    }
    
    /**
     * View a journal along with its entries
     * @param id the journal's ID
     * @return a view that display a journal along with its entries
     * @throws SQLException
     * @throws NamingException 
     */
    public String viewJournal(long id) throws SQLException, NamingException{
        try {
            journal = journalDAO.getJournal(id);
            FacesContext context = FacesContext.getCurrentInstance();
            HttpServletRequest request = (HttpServletRequest)context.getExternalContext().getRequest();
            String remoteUser = request.getRemoteUser();
            if (remoteUser == null) {
                isModifiable = false;
            }
            else{
                isModifiable = remoteUser.equals(journal.getAuthor());
            }
            
            return "viewJournal";
        } catch (SQLException | NamingException ex) {
            Logger.getLogger(JournalController.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }
    
    /**
     * Retrieve a list of journals created by the current logged in user
     * @return a view that display the mentioned list
     * @throws SQLException
     * @throws NamingException 
     */
    public String myJournals() throws SQLException, NamingException{
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest)context.getExternalContext().getRequest();
        String author = request.getRemoteUser();
        journalList = journalDAO.getJournals(author);
        return "myJournals";
    }
    
    /**
     * Retrieve a list of journals that contain entries from the most recent date
     * @return a list of journals that contain entries from the most recent date
     * @throws SQLException
     * @throws NamingException 
     */
    public List<JournalDTO> getLastestJournals() throws SQLException, NamingException{
        return journalDAO.getLatestJournals();
    }
    
    /**
     * Retrieve a list of journals that match the search key
     * @return a view that display the list
     * @throws SQLException
     * @throws NamingException 
     */
    public String searchJournal() throws SQLException, NamingException{
        journalList = journalDAO.search(searchKey);
        return "search";
    }
    
    /**
     * Retrieve a journal based on its ID for updating
     * @param id the journal's ID
     * @return a view that allow user to edit the entry
     * @throws SQLException
     * @throws NamingException 
     */
    public String editJournal(long id) throws SQLException, NamingException{
        journal = journalDAO.getJournal(id);
        return "editJournal";
    }
    
    /**
     * Edit the journal from user's submitted form
     * @param id the journal's ID
     * @param newTitle the journal's new title
     * @return a view that display the newly updated journal
     * @throws SQLException
     * @throws NamingException 
     */
    public String editJournal(long id, String newTitle) throws SQLException, NamingException{
        journalDAO.updateJournal(id, newTitle);
        return viewJournal(id);
    }
    
    /**
     * Delete user's journals based on the checkedJournals variable
     * @return a view display the user's remaining journals
     * @throws NamingException
     * @throws SQLException 
     */
    public String deleteSelectedJournals() throws NamingException, SQLException{
        ArrayList<Long> selectedIds = new ArrayList<>();
        for(Long journalID : checkedJournals.keySet()){
            if (checkedJournals.get(journalID) == true){
                selectedIds.add(journalID);
            }
        }
        
        journalDAO.deleteJournals(selectedIds.toArray(new Long[0]));
        return myJournals();
    }
    
    /**
     * Delete a single journal based on its ID
     * @param journalID the journal ID
     * @return a view display the user's remaining journals
     * @throws NamingException
     * @throws SQLException 
     */
    public String deleteJournal(long journalID) throws NamingException, SQLException{
        journalDAO.deleteJournals(new Long[]{journalID});
        return myJournals();
    }
    
    /**
     * Retrieve an entry for updated
     * @param entryID the entry unique ID
     * @return a view that allow user to update the entry
     * @throws SQLException
     * @throws NamingException 
     */
    public String editEntry(long entryID) throws SQLException, NamingException{
        entry = entryDAO.getEntry(entryID);
        journal = journalDAO.getJournal(entry.getJournalID());
        return "newEntry";
    }
    
    /**
     * Display a view for the user to create new entry
     * @param journalID the ID of the journal that the entry belongs to
     * @return a view that allow user to create new entry
     * @throws SQLException
     * @throws NamingException 
     */
    public String newEntry(long journalID) throws SQLException, NamingException{
        entry = new EntryDTO();
        journal = journalDAO.getJournal(journalID);
        return "newEntry";
    }
    
    /**

JoJo/src/java/uts/aip/CuuSonDang/Controller/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts.aip.CuuSonDang.Controller;

import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import uts.aip.CuuSonDang.DAO.AccountDAO;

/**
 * This class allow the user to login/logout of the system
 * @author Cuu Son Dang
 */
@Named
@RequestScoped
public class LoginController implements Serializable {
    private AccountDAO accountDAO = new AccountDAO();
    
    private String username;
    private String password;
    private String errorMessage;
    
    /**
     * The unique username of the user
     * @return 
     */
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * The user's password
     * @return 
     */
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    /**
     * A user friendly message to be displayed to user
     * @return 
     */
    public String getErrorMessage() {
        return errorMessage;
    }
    
    /**
     * Login a user based on the username and password
     * @return the index view if the user login successfully, or return to login page if there is error during login.
     */
    public String login() {
        try {
            FacesContext context = FacesContext.getCurrentInstance();
            HttpServletRequest request = (HttpServletRequest)context.getExternalContext().getRequest();
            request.login(username, password);
            return "index";
        } catch (ServletException ex ) {
            errorMessage = "Login failed, please try again";
            Logger.getLogger(LoginController.class.getName()).log(Level.SEVERE, null, ex);
            return "login";
        }
    }
    
    /**
     * Log a user out of the system
     * @return the index view if user log out successfully
     * @throws javax.servlet.ServletException
     */
    public String logout() throws ServletException{
        try {
            FacesContext context = FacesContext.getCurrentInstance();
            HttpServletRequest request = (HttpServletRequest)context.getExternalContext().getRequest();
            request.logout();
            return "index";
        } catch (ServletException ex) {
            Logger.getLogger(LoginController.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }
}

JoJo/src/java/uts/aip/CuuSonDang/Controller/UserController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts.aip.CuuSonDang.Controller;

import java.io.Serializable;
import java.sql.SQLException;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.naming.NamingException;
import javax.servlet.http.HttpServletRequest;
import uts.aip.CuuSonDang.DAO.AccountDAO;
import uts.aip.CuuSonDang.DTO.AccountDTO;

/**
 * This class is used to retrieve the information of the logged in user
 * @author Cuu Son Dang
 */
@Named
@SessionScoped
public class UserController implements Serializable {
    private AccountDTO loggedInUser = null;
    private AccountDAO accountDAO = new AccountDAO();
    
    /**
     * Indicate if the user is logged in or not
     * @return true if the user is logged in, false otherwise.
     */
    public boolean getIsLoggedIn(){
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest)context.getExternalContext().getRequest();
        return request.getRemoteUser() != null;
    }
    
    /**
     * Retrieve the information of the logged in user
     * @return the account detail of the logged in user
     * @throws NamingException
     * @throws SQLException 
     */
    public AccountDTO getLoggedInUser() throws NamingException, SQLException {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest)context.getExternalContext().getRequest();
        if (loggedInUser == null || !loggedInUser.getUsername().equals(request.getRemoteUser())){
            loggedInUser = accountDAO.findAccount(request.getRemoteUser());
        }
        
        return this.loggedInUser;
    }
}

JoJo/web/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

    <h:body>
        <ui:composition template="./template.xhtml">
           
            
            <ui:define name="body">
                Some error occurs, please try again.
            </ui:define>
        </ui:composition>
    </h:body>
</html>

JoJo/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:jj="http://java.sun.com/jsf/composite/ezcomp">

    <h:body>
        <ui:composition template="./template.xhtml">
            <ui:define name="body">
                <div class="row">
                    <div class="col-sm-9" style="min-width: 500px;">
                        <jj:journalList journalList="#{journalController.lastestJournals}"/>
                    </div>

                    <div class="col-sm-3 hidden-xs">
                        <div class="panel panel-default" style="position: fixed;">
                            <div class="panel-body">
                                <p>Best destinations</p>
                                <ul class="list-unstyled">
                                    <li><a href="#">Paris - France</a></li>
                                    <li><a href="#">Grand Place - Belgium</a></li>
                                    <li><a href="#">Blue Mountains - NSW Australia</a></li>
                                    <li><a href="#">Melbourne - NSW Australia</a></li>
                                    <li><a href="#">Melbourne</a></li>
                                    <li><a href="#">Melbourne</a></li>
                                    <li><a href="#"><small>See more</small></a></li>
                                </ul>

                                <hr/>

                                <p>Most favorited trips</p>
                                <ul class="list-unstyled">
                                    <li><a href="#">Summer in Europe</a></li>
                                    <li><a href="#">Adventure to Southeast Asia</a></li>
                                    <li><a href="#">Into the jungle</a></li>
                                    <li><a href="#">Australia trip</a></li>
                                    <li><a href="#">Australia trip</a></li>
                                    <li><a href="#">Australia trip</a></li>
                                    <li><a href="#"><small>See more</small></a></li>
                                </ul>

                                <hr/>

                                <p>Popular travellers</p>
                                <ul class="list-unstyled">
                                    <li><a href="#">Cuu Son Dang</a></li>
                                    <li><a href="#">Vu Tran</a></li>
                                    <li><a href="#">Going places kid</a></li>
                                    <li><a href="#">Bear Grylls</a></li>
                                    <li><a href="#">Pokemon Go</a></li>
                                    <li><a href="#">Pokemon Go</a></li>
                                    <li><a href="#"><small>See more</small></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

JoJo/web/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:jj="http://java.sun.com/jsf/composite/ezcomp"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>

        <!-- jQuery -->
        <h:outputScript library="jquery" name="js/jquery-1.12.0.min.js"/>

        <!-- Boostrap-->
        <h:outputStylesheet library="bootstrap" name="css/bootstrap.min.css"/> 
        <h:outputScript library="bootstrap" name="js/bootstrap.min.js"/>

        <!-- Font awesome -->
        <h:outputStylesheet library="font-awesome" name="css/font-awesome.min.css"/>

        <ui:insert name="head"></ui:insert>

        <!--	 Boostrap Dialog 
                <link rel="stylesheet" href="./css/bootstrap-dialog.css"/>
                <script src="./js/bootstrap-dialog.js"></script>-->

    </h:head>
    <h:body>
        <!-- Header -->
        <div class="navbar navbar-inverse navbar-fixed-top hidden-xs">
            <div class="container">

                <!-- Logo -->
                <div class="nav-header">
                    <h:link outcome="index" class="navbar-brand">JoJo</h:link>
                </div>
                <!-- End logo -->

                <!-- Search bar -->
                <h:form class="navbar-form navbar-left">
                    <div class="form-group">
                        <h:inputText class="form-control" value="#{journalController.searchKey}"/>
                    </div>
                    <h:commandLink action="#{journalController.searchJournal()}" class="btn btn-default">Search&nbsp;<span class="fa fa-search"></span></h:commandLink>
                </h:form>
                <!-- End search bar -->

                <!-- User menu-->
                <h:panelGroup rendered="#{userController.isLoggedIn}">
                    <div class="nav navbar-nav navbar-right">
                        <div style="padding-top: 5px;">
                            <jj:profilePicture imgSrc="#{userController.loggedInUser.profilePicture}" style="width: 40px; height:40px;"/>
                        </div>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <li>


                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Hello, #{userController.loggedInUser.fullName} <span class="caret"></span>
                                <h:form class="dropdown-menu">
                                    <li><h:link outcome="newJournal" value="New Journal"/></li>
                                    <li><h:commandLink value="My Journals" action="#{journalController.myJournals()}"/></li>
                                    <li role="separator" class="divider"></li>
                                    <!--<li><a href="#">Edit profile</a></li>-->
                                    <li><h:commandLink value="Logout" action="#{loginController.logout()}"/></li>
                                </h:form>
                            </a>



                        </li>
                    </ul>
                </h:panelGroup>
                <!-- End user menu -->

                <!-- Quick login -->
                <h:panelGroup rendered="#{!userController.isLoggedIn}"> 
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <h:form class="navbar-form">
                                <div class="form-group">
                                    <h:inputText value="#{loginController.username}" class="form-control" pt:placeholder="Username"/>
                                </div>
                                <div class="form-group">
                                    <h:inputSecret value="#{loginController.password}" class="form-control" pt:placeholder="Password"/>
                                </div>
                                <div class="form-group">
                                    <h:commandButton value="Login" class="btn btn-success" action="#{loginController.login()}">
                                        <f:param name="username" value="#{username}" />
                                        <f:param name="password" value="#{password}" />
                                    </h:commandButton>
                                </div>
                                <div class="form-group">
                                    <h:link value="Register" outcome="register" class="btn btn-primary"/>
                                </div>
                            </h:form>
                        </li>
                    </ul>
                </h:panelGroup>
                <!-- End quick login-->
            </div>
        </div>
        <!-- End header -->

        <!-- Site body -->
        <div class="container" style="margin-top: 70px;">
            <ui:insert name="body"></ui:insert>
        </div>
        <!-- End site body -->
    </h:body>
</html>

JoJo/web/viewJournal.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:body>
        <ui:composition template="./template.xhtml">
            
            <ui:define name="head">
                <h:outputStylesheet library="bootstrap" name="css/bootstrap-dialog.css"/>
                <h:outputScript library="bootstrap" name="js/bootstrap-dialog.js"/>
                <script type="text/javascript">
                    $(function(){
                        $(".remove-entry-btn").click(function(){
                            var removeBtn = $(this).siblings(".remove-entry")[0];
                            BootstrapDialog.show({
				type: BootstrapDialog.TYPE_WARNING,
				title: "Confirm delete",
				message: "Please confirm if you really want to delete this entry",
				buttons: [{
					label: "Yes",
					cssClass: "btn-warning",
					action: function(dialog){
						$(removeBtn).click();
					}
				},{
					label: "No",
					action: function(dialog){
						dialog.close();
					}
				}]
                            });
                        });
                    });                
    
                </script>
            </ui:define>
            
            <ui:define name="body">
                <div class="col-md-11">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h2>#{journalController.journal.title}</h2>
                        </div>
                    </div>

                    <h:panelGroup rendered="#{journalController.journal.entries.size() == 0}">
                        <div class="alert alert-warning" role="alert">There are no entries in this journal</div>
                    </h:panelGroup>
                    <ui:repeat value="#{journalController.journal.entries}" var="entry">
                        <div id="#{entry.date}" class='panel panel-default'>
                            <div class='panel-body'>
                                <h3>
                                    <h:outputText value="#{entry.date}"><f:convertDateTime pattern="dd/MM/yyyy"/></h:outputText>
                                </h3>
                                <p>
                                    <h:outputText value="#{entry.content}" escape="false"/>
                                </p>

                                <h:panelGroup>
                                    <h:form>
                                        <h:inputHidden value="#{journalController.journal.journalID}"/>
                                        <h:commandLink class="btn btn-primary" action="#{journalController.editEntry(entry.entryID)}" rendered="#{journalController.isModifiable}">
                                            <i class='fa fa-edit'></i> Edit
                                        </h:commandLink>
                                        &nbsp;
                                        <h:outputLink value="#" class="btn btn-danger remove-entry-btn" rendered="#{journalController.isRemovable}">
                                            <i class='fa fa-remove'></i> Remove
                                        </h:outputLink>
                                        <h:commandLink class="remove-entry" value="test" style="display: none;" actionListener="#{journalController.deleteEntry(entry.entryID)}" rendered="#{journalController.isRemovable}" />
                                    </h:form>
                                </h:panelGroup>
                            </div>
                        </div>
                    </ui:repeat>
                </div>

                <div class="col-md-1">

                    <h:panelGroup style="position: fixed;">
                        <h:panelGroup rendered="#{journalController.isModifiable}">
                            <h:form> 
                                <h:inputHidden value="#{journalController.journal.journalID}"/>
                                <h:commandButton action="#{journalController.newEntry(journalController.journal.journalID)}" 
                                                 class="btn btn-success" value="New entry"/>
                                <h:messages/>
                            </h:form>
                            <br/>
                        </h:panelGroup>

                        <h:panelGroup rendered="#{journalController.journal.entries.size() > 0 }">
                            <table class="table table-striped table-bordered">
                                <tbody>
                                    <ui:repeat value="#{journalController.journal.entries}" var="entry">
                                        <tr><td><a href="##{entry.date}"><h:outputText value="#{entry.date}"></h:outputText></a></td></tr>
                                    </ui:repeat>
                                </tbody>
                            </table>
                        </h:panelGroup>
                    </h:panelGroup>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

JoJo/web/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:body>
        <h4 class="alert alert-success">Your account has been registered successfully. You can now <h:link outcome="login" value="login"/> or return to <h:link outcome="index" value="home page"/></h4>
    </h:body>
</html>